version: '3'
services:
  mysql:
    image: mysql
    ports:
      - 33061:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Passw0rd
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
    driver: local